---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: k8s-example
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: k8s-example
    component: echo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-example
        component: echo
    spec:
      containers:
      - name: echo
        image: gcr.io/fulgid-dev/echo:v2
        ports:
        - containerPort: 8080
