---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: k8s-example
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: k8s-example
    component: proxy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-example
        component: proxy
    spec:
      containers:
      - name: proxy
        image: gcr.io/fulgid-dev/proxy:v1
        ports:
        - containerPort: 8080
